### ISSUE TITLE
dataset and paper

### ISSUE THREAD

**Issue by Haifa-eng** [luciaquirke/sleep-apnea#1]
Hi 

Can you attach your datasets please also if you have reference to your paper.

**Comment by luciaquirke** [comment]
Hi there,

The dataset is from the open-access [MIT-BIH Polysomnographic Database](https://physionet.org/content/slpdb/1.0.0/). The data is easily accessed using the [WFDB package](https://archive.physionet.org/physiotools/wfdb.shtml). I didn't publish a paper for this project.

**Comment by sameerg07** [comment]
hey which python version did you use while developing?

**Comment by luciaquirke** [comment]
I can't remember sorry, but it should work with any python version between 3.5 and 3.8.
